version: '3.5'
name: chat_app

networks:
  inside_net:
    name: inside_net
    driver: bridge

services: 
  client:
    build:
      context: ./client
      args: 
        - 'VITE_SERVER_URL=https://${SERVER_HOST}:${PORT}'
    container_name: client
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment: 
      - 'VITE_SERVER_URL=https://${SERVER_HOST}:${PORT}'
      - 'CLIENT_PORT=${CLIENT_PORT}'
      - 'CLIENT_HOST=${CLIENT_HOST}'

  server:
    build: ./server
    container_name: server
    ports:
      - '${PORT}:${PORT}'
    environment:
      - 'NODE_ENV=${NODE_ENV}'
      - 'PORT=${PORT}'
      - 'SERVER_HOST=${SERVER_HOST}'
      - 'DB_HOST=postgres_db'
      - 'REDIS_HOST=redis'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'CLIENT_URL=http://${CLIENT_HOST}:${CLIENT_PORT}'
    depends_on:
      - postgres_db
      - redis
    networks:
      - inside_net

  postgres_db:
    image: postgres:16.0
    container_name: postgres_db
    environment: 
      - 'POSTGRES_DB=chatapp_db'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    volumes:
      - ./server/chatapp_db.gz:/var/backups/chatapp_db.gz:ro
      - ./server/fill-db.sh:/docker-entrypoint-initdb.d/fill-db.sh
      - ./server/postgres_data:/var/lib/postgresql/data
    networks:
      - inside_net

  redis:
    image: redis:7.2.1
    container_name: redis
    networks:
      - inside_net

  adminer:
    image: adminer:4.8.1
    environment: 
      - 'ADMINER_DEFAULT_SERVER=postgres_db:5432'
    restart: always
    ports:
      - 8080:8080
    networks:
      - inside_net
