FROM node:20
WORKDIR /usr/app
EXPOSE 80

RUN apt-get update && apt install -y git-all
RUN git clone https://github.com/Raytem/NestJS_chatApp_server.git
WORKDIR /usr/app/NestJS_chatApp_server

RUN npm install
CMD npm start

